version: "3.9"

services:
  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=s3,dynamodb,cloudformation,sts,ssm,iam,kms,lambda
      - AWS_DEFAULT_REGION=ap-southeast-2
      - DEBUG=1
    ports:
      - 4566:4566
